//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Empresa_Fabricacion
{
    using System;
    using System.Collections.Generic;
    
    public partial class Materiales
    {
        public int MaterialId { get; set; }
        public string Nombre { get; set; }
        public double Precio { get; set; }
        public int Stock { get; set; }
        public int FabricacionId { get; set; }
        public int ProveedorId { get; set; }
    
        public virtual Fabricaciones Fabricaciones { get; set; }
        public virtual Proveedores Proveedores { get; set; }
    }
}
